// <auto-generated />
using System;
using KosTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KosTracker.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KosTracker.Core.Kosten", b =>
                {
                    b.Property<float>("Ausgabe")
                        .HasColumnType("real");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Kosten");
                });

            modelBuilder.Entity("KosTracker.Core.KostenSoll", b =>
                {
                    b.Property<float>("Bekleidung")
                        .HasColumnType("real");

                    b.Property<float>("Gesundheit")
                        .HasColumnType("real");

                    b.Property<float>("Lebensmittel")
                        .HasColumnType("real");

                    b.Property<float>("Miete")
                        .HasColumnType("real");

                    b.Property<float>("Nebenkosten")
                        .HasColumnType("real");

                    b.Property<float>("Transport")
                        .HasColumnType("real");

                    b.Property<float>("Unterhaltung")
                        .HasColumnType("real");

                    b.Property<float>("Versicherung")
                        .HasColumnType("real");

                    b.ToTable("kostenSoll");
                });

            modelBuilder.Entity("KosTracker.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
